[tool.bumpversion]
current_version = "0.2.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
commit = true
tag = true
tag_name = "v{new_version}"
tag_message = "Version {new_version}"
message = "Version {new_version}"

[[tool.bumpversion.files]]
filename = "src/kd.sh"
search = 'readonly VERSION="{current_version}"'
replace = 'readonly VERSION="{new_version}"'

[[tool.bumpversion.files]]
filename = "test/test.bats"
search = "kd version {current_version}"
replace = "kd version {new_version}"
